# Site settings
title: Lea Fairbanks
email: lea.rae.fairbanks@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write neat software.
baseurl:  # the subpath of your site, e.g. /blog/
url: https://leafairbanks.com # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  darunada

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
#  adventures:
#    output: true
#    permalink: /adventures/:path/


