---
title: Lea Fairbanks
timezone: UTC
collections:
  portfolio:
    title: Portfolio
    output: true
    permalink: "/portfolio/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@leaflab.sh
description: 
url: https://leafairbanks.com
github_username: darunada
markdown: kramdown
highlighter: rouge
paginate: 15
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
